- hosts: localhost
  connection: local
  vars:
    - defaults/main.yml
    - vars/main.yml
    
  tasks:
    - debug:
        msg: "Ansible Pull"

    - include: tasks/manage_users.yml

    - include: tasks/manage_sudoers.yml
